"""Initial migration for enquiries table

Revision ID: a29e5bbf4fb2
Revises: 
Create Date: 2026-09-17 23:12:40.517957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29e5bbf4fb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('service', sa.String(length=80), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('project_location', sa.String(length=150), nullable=False),
    sa.Column('budget', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('new', 'contacted', 'in_progress', 'closed')", name='valid_enquiry_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enquiries_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enquiries_status'))
        batch_op.drop_index(batch_op.f('ix_enquiries_created_at'))

    op.drop_table('enquiries')
    # ### end Alembic commands ###
